### ISSUE TITLE
Please add dataset if possible

### ISSUE THREAD

**Issue by SerjSmor** [chathuranga95/SoundEventClassification#1]

**Comment by chathuranga95** [comment]
Please refer to modified [README.md](https://github.com/chathuranga95/SoundEventClassification/blob/master/README.md)

Closing the issue with fc1637a53fefa0e1d16bb285f62e42bccdae7eb2

**Comment by nkw97** [comment]
Anyone Know how to create STFT_features/stft_257_1 folder because i getting Error
