### ISSUE TITLE
Please add Keras 'h5' model if possible

### ISSUE THREAD

**Issue by SerjSmor** [chathuranga95/SoundEventClassification#2]

**Comment by chathuranga95** [comment]
You can generate the model by following the steps given in the modified [README.md](https://github.com/chathuranga95/SoundEventClassification/blob/master/README.md)

Closing the issue with fc1637a53fefa0e1d16bb285f62e42bccdae7eb2

**Comment by nkw97** [comment]
how to fix this issue 
![image](https://user-images.githubusercontent.com/50964739/126958800-2c5cb3f2-525d-4d74-989c-a942c492a3dd.png)
